### ISSUE TITLE
Error after running example

### ISSUE THREAD

**Issue by vapor99** [anfederico/Stocktalk#2]
I keep getting an error that TwitterAxe cannot be found.  Its very strange because I have installed all the requirements.txt and pip installed stocktalk -- all in a virtualenv.  All paths look correct.  Any ideas?

(venv) [pez:~/dev/stocktalk]$ python ./mine.py                                                                                     (master✱) 
Traceback (most recent call last):
  File "./mine.py", line 1, in <module>
    from stocktalk import TwitterAxe
  File "/Users/pez/dev/Stocktalk/stocktalk/__init__.py", line 1, in <module>
    from TwitterAxe import TwitterAxe
ImportError: No module named 'TwitterAxe'

**Comment by anfederico** [comment]
It should be working, still having issues?

**Comment by beeedy** [comment]
encountering the same error

**Comment by anfederico** [comment]
What version of Python are you using? Also, can I see the .py you're running.

**Comment by beeedy** [comment]
Python 2.7 on Ubuntu 16.04

Problem was resolved after uninstalling and reinstalling Stocktalk

**Comment by anfederico** [comment]
Great to hear!

**Comment by rupeshmacherla92** [comment]
from stocktalk import TwitterAxe

Traceback (most recent call last):
  File "<pyshell#7>", line 1, in <module>
    from stocktalk import TwitterAxe
  File "C:\Python27\lib\site-packages\stocktalk\__init__.py", line 1, in <module>
    from TwitterAxe import TwitterAxe
  File "C:\Python27\lib\site-packages\stocktalk\TwitterAxe.py", line 10, in <module>
    from pandas               import DataFrame
ImportError: No module named pandas
When I am import TwitterAxe, I can get this error message. Please Help me

**Comment by anfederico** [comment]
"ImportError: No module named pandas"

This is basically telling you that it cannot find the pandas library. Make sure you have it installed.

pip install pandas

**Comment by rupeshmacherla92** [comment]
Hi anfederico, Thanks for your suggestion, I resolve the previous error with your suggestion.
axe.mine("Alfamart", minePeriod, requestFrequency, analyzeFrequency, requestAmount, similarityCutoff)
But I execute above code, I get an error like below
Traceback (most recent call last):
  File "C:/Users/Rupesh Macherla/Desktop/AlfamartTwitter.py", line 20, in <module>
    axe.mine("Alfamart", minePeriod, requestFrequency, analyzeFrequency, requestAmount, similarityCutoff)
  File "C:\Python27\lib\site-packages\stocktalk\TwitterAxe.py", line 105, in mine
    schedule.run_pending()
  File "C:\Python27\lib\site-packages\schedule\__init__.py", line 462, in run_pending
    default_scheduler.run_pending()
  File "C:\Python27\lib\site-packages\schedule\__init__.py", line 75, in run_pending
    self._run_job(job)
  File "C:\Python27\lib\site-packages\schedule\__init__.py", line 129, in _run_job
    ret = job.run()
  File "C:\Python27\lib\site-packages\schedule\__init__.py", line 377, in run
    ret = self.job_func()
  File "C:\Python27\lib\site-packages\stocktalk\TwitterAxe.py", line 90, in analyzeGroup
    "sentiment" : sentimentScore(self.groupedTweets),
  File "C:\Python27\lib\site-packages\stocktalk\TwitterAxe.py", line 46, in sentimentScore
    score = SentimentIntensityAnalyzer().polarity_scores(text)["compound"]
  File "C:\Python27\lib\site-packages\nltk\sentiment\vader.py", line 204, in __init__
    self.lexicon_file = nltk.data.load(lexicon_file)
  File "C:\Python27\lib\site-packages\nltk\data.py", line 808, in load
    opened_resource = _open(resource_url)
  File "C:\Python27\lib\site-packages\nltk\data.py", line 926, in _open
    return find(path_, path + ['']).open()
  File "C:\Python27\lib\site-packages\nltk\data.py", line 648, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource
  u'sentiment/vader_lexicon.zip/vader_lexicon/vader_lexicon.txt'
  not found.  Please use the NLTK Downloader to obtain the
  resource:  >>> nltk.download()
  Searched in:
    - 'C:\\Users\\Rupesh Macherla/nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
    - 'C:\\Python27\\nltk_data'
    - 'C:\\Python27\\lib\\nltk_data'
    - 'C:\\Users\\Rupesh Macherla\\AppData\\Roaming\\nltk_data'
    - u''
Please give your suggestion to solve the above error.
Thanks.

**Comment by anfederico** [comment]
Yes you need to download some corpus data to do sentiment analysis. Try either of these commands in your terminal:

stocktalk-corpus
or
python -m nltk.downloader vader_lexicon

**Comment by ktdbest2** [comment]
Hi anfederico,

Will this library now work for python 3.5. I am getting error 'no module named 'TwitterAxe'
